"""empty message

Revision ID: bb741010fea3
Revises: b35fcbf83681
Create Date: 2023-08-09 17:12:05.305311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb741010fea3'
down_revision = 'b35fcbf83681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('media')
    # ### end Alembic commands ###
    op.execute(f"ALTER TABLE medias SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('media_type', sa.VARCHAR(), nullable=False),
    sa.Column('media_url', sa.VARCHAR(), nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medias')
    # ### end Alembic commands ###
