"""empty message

Revision ID: bbd3f64458b7
Revises: fefc1cf2e5e2
Create Date: 2023-09-14 17:41:33.890686

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'bbd3f64458b7'
down_revision = 'fefc1cf2e5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(), nullable=True))

    # ### end Alembic commands ###
    if environment == "production":
         op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
